### PR TITLE
Support Webpack 5

### PR DESCRIPTION
**Pull request by samageloff**

### CODE REVIEW

**Comment by samageloff** [comment]
@MikaAK this is just an initial commit, to get dependencies up to date, and to see where the test failures occur. I'll take a stab at getting the compiler logic updated per this PR: https://github.com/bugsnag/webpack-bugsnag-plugins/pull/29/files

**Comment by MikaAK** [comment]
@samageloff  I just noticed this the close message, sorry about missing this. Would you like to get this merged? I would be grateful for the assistance.

**Comment by samageloff** [comment]
Hey @MikaAK, no worries at all. This PR wasn't ready to merge, and I was finding that I could not devote any time to it. Didn't want to keep it open indefinitely. Might be used as a reference for a future PR, however.

**Comment by MikaAK** [comment]
The struggles of OSS maintainers is always time!! No worries 😄  Thanks for a reference!!

**Pull request closed without merging**
