### PR TITLE
Update cdnizer to resolve downstream semver vuln

### PR DESCRIPTION
**Pull request by noqcks**
This resolves all the `npm audit` issues people are having, as mentioned here https://github.com/MikaAK/s3-plugin-webpack/issues/98#issuecomment-417545914

The PR on cdnizer that resolved downstream vulnerability here: https://github.com/OverZealous/cdnizer/pull/33#issuecomment-446582740

### CODE REVIEW

**Comment by noqcks** [comment]
cc: @MikaAK

**Comment by MikaAK** [comment]
Thanks @noqcks! Nice to see Lighthouse grads in the field 😉

**Comment by noqcks** [comment]
Thanks @MikaAK could we cut a new release for this 🙏

**Comment by MikaAK** [comment]
@noqcks  Done! 1.0.3

**Pull request merged**
