### PR TITLE
Webpack style include / exclude rules

### PR DESCRIPTION
**Pull request by datapimp**
This makes the file include / exclude rules behave more similarly to webpack.

Note -- wasn't able to run the tests, will get S3 credentials and try to do so

### CODE REVIEW

**Comment by MikaAK** [comment]
Nice add,  one thing is what is line 64 doing in helpers file? I find it a bit unreadable, also if they provide a string we shouldn't manipulate it in any way due to confusion down the line.  It should just be passed straight into RegExp, what do you think?

**Comment by datapimp** [comment]
Hi so that is the same regexp webpack uses to match paths.  See https://github.com/webpack/webpack/blob/master/lib/LoadersList.js#L22

**Comment by datapimp** [comment]
So -- on second thought, webpack is matching the absolute path I believe; 

however as a user of this plugin and supplying a string value i might not expect to need to do that, so I think you have a point.  Your call.  

I mainly care about the function argument but to keep it consistent  figured make it exactly like webpacks behavior

**Comment by MikaAK** [comment]
I would say we not do that,  we only need to ignore by name not absolute path :)

**Comment by datapimp** [comment]
Ok I made the change and added some examples to the README.

**Comment by MikaAK** [comment]
Perfect! If this can just get a couple of quick tests (one for include and one for exclude) I'll merge it in 😄

**Pull request merged**
