### PR TITLE
Improve test error output

### PR DESCRIPTION
**Pull request by mlarraz**
Just logging the stack trace (formatted correctly), for readability.

Before and after:

imageimage

### CODE REVIEW

**Comment by mlarraz** [comment]
@MikaAK would love some help to get the build passing. Is it just some missing environment variables?

**Comment by MikaAK** [comment]
That's probably the case I'll pull them over from travis later today

**Comment by MikaAK** [comment]
I've never really used GH actions, I setup the secrets though for AWS_ACCESS_KEY, AWS_BUCKET, AWS_REGION, AWS_SECRET_ACCESS_KEY, NODE_ENV

let me know if there's further steps!

**Comment by mlarraz** [comment]
I set up this PR to pull them into the environment: https://github.com/MikaAK/s3-plugin-webpack/pull/155

Still doesn't seem to be working though

**Pull request merged**
