### PR TITLE
Use AWS S3 SDK directly

### PR DESCRIPTION
**Pull request by johnf**
Builds on work by @soaa to move to aws-sdk for s3 uploads.
@johnf contribution is fixing mime types

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@johnf - You are going to run into issues trying to land a PR with multiple committers unless they are active & you can get them to sign the CLA as well.

If the idea is to just attribute credit for work, that may be better mentioned in the PR itself as opposed to going the multi-person pull request route.

**Comment by johnf** [comment]
@d3viant0ne I'll wait to see if @soaa pops up.

I assume if he doesn't I should do my own rewrite. I'd be in breach of the CLA if I just used @soaa's code right? Even if I attributed it in the notes?

**Comment by soaa** [comment]
@johnf I just signed the CLA.
I'm glad I'm the part of the contribution.

But one thing you should know that is I'm not the expert of javascript and the patch was just for my personal project. The code was not fully tested.

**Comment by johnf** [comment]
@soaa Thanks. I've had a look at your changes and they look fine. I've also confirmed the tests work. So this should be ready for merging.

Only possible question is around version for aws-sdk. I bumped this up to ensure we have V4 signing for S3 which is needed in newer regions. Not sure if I've bumped it too high?

**Comment by johnf** [comment]
Oh an tests are failing because the mime library I picked needs at least node 6.
I could revert that to 1.x series of ```mime``` but node 5 is pretty old now so maybe just up the tests?
I'll do that in this PR now.

**Comment by deiga** [comment]
@johnf Could you look at the failures and fix them? :)

@d3viant0ne Better yet. Can we just get this instead? :)

**Comment by MikaAK** [comment]
Awesome work, looking at the travis it seems that the ENV variables aren't making it into the containers even being set. I'll figure this out with @d3viant0ne's help and try and get pr's rolling again

**Pull request merged**
